name: molssi-training
channels:
  - conda-forge
  - defaults
dependencies:
  - "python>=3.11"
  - openjdk # for java (required for tabula)
  - pip
  - notebook # jupyter noteboook
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ocrmypdf
  - scikit-learn
  - statsmodels
  - rdkit

  - pip:
    - tabula-py
    - plotly
    - kaleido
